_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  announcements_feed: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_list_override: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_translation: 0
  contact: 0
  content_access: 0
  content_moderation: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  eca: 0
  eca_content_access: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_group_migrate: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_captcha: 0
  inline_entity_form: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pfdp: 0
  redirect: 0
  redirect_404: 0
  redirect_domain: 0
  reroute_email: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  smtp: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_taxonomy_term_name_depth: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  seven: 0
  adminimal_theme: 0
profile: standard
