_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: false
element_name: home
time_limit: 5
expire: 300
form_settings:
  user_register_form: true
  user_pass: true
  contact_message_feedback_form: false
  contact_message_personal_form: true
  node_article_form: false
  node_author_form: false
  node_book_form: false
  node_meeting_form: false
  node_movie_ticket_form: false
  node_news_article_form: false
  node_news_article_2_form: false
  node_page_form: false
  node_sample_form: false
  node_vendor_form: false
  comment_comment_form: false
  comment_new_comment_form: false
