_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    de: de
    ru: ru
    ar: ar
    es: es
  domains:
    en: ''
    de: ''
    ru: ''
    ar: ''
    es: ''
selected_langcode: site_default
